---
title: "STAT462 Assignment 1"
author:  
 -  Simon Clark (XXXXXXXX) 
 -  David Ewing (82171165)  
 -  Xia Yu (62380486) 
date: "`r Sys.Date()`"

params:
  pthreshold: 0.25  # DEE: pthreshold is a parameter for possum correlation. 
                    # it is made visible here in the yaml code. 
                    # A better explaination will be provided after discussion 
                    # with the team. 


output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
# DEE: This chunk was set up with the aid of ChatGPT
#      The intent is to load updates quietly thus not
#      spending undue time with the logistics of getting 
#      setup. 

options(repos = c(CRAN = "https://cran.stat.auckland.ac.nz/"))

# Required packages
required_packages <- c("conflicted", "ggplot2", "dplyr", "class", "tidyverse",
                       "flextable", "skimr", "GGally")

# Install and load missing packages in a single step
for (pkg in required_packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
  }
  library(pkg, character.only = TRUE)  # Load package after installation check
}

conflict_prefer("filter", "dplyr"); conflict_prefer("select", "dplyr")

# THIS IS THE MANUAL WAY. I am happy to help you get your
# library into the loop above if you have problems doing 
# this on your own. 
# library(ggplot2)
# library(dplyr)
# library(class)
# library(tidyr)
# library(flextable)
# library(skimr)
```

```{r just-checkin, include=F, eval=F}
  
  # is the folder and file structure 
  # constructed correctly? 
  dir.exists("../code/")
  file.exists("../code/question1.Rmd")
  file.exists("../code/question2.Rmd")
  file.exists("../code/question3.Rmd")
```

# Load all Data 

```{r load-common-data, eval=FALSE, include=FALSE }
# Load and preprocess dataset
# eval=FALSE until agreed by all parties. 
  zip_path <- "../data/datasets.zip"
  if (file.exists(zip_path)) {
    braking <- read.csv(unz(zip_path, "braking.csv"))
    income  <- read.csv(unz(zip_path, "income.csv"))
    possums <- read.csv(unz(zip_path, "possums.csv"))
  } else {
    stop(paste(zip_path, " not found."))
  }
``` 

# Braking Distance


```{r, child="../code/question1.Rmd"}
```



# Filipino Household Income



```{r, child="../code/question2.Rmd", eval=T}
```


# Predicting Possum Age


```{r load-question3, child="../code/question3.Rmd", eval=T}
```
