---
title: "STAT462 Assignment 1"
author:  
 -  Simon Clarke (97211898) 
 -  David Ewing (82171165)  
 -  Xia Yu (62380486) 

date: "`r format(Sys.time(), '%Y-%m-%d %H:%M')`"
output: 
  pdf_document:
    latex_engine: xelatex
header-includes:
  - \usepackage{fancyvrb}
  - \RecustomVerbatimEnvironment{verbatim}{Verbatim}{xleftmargin=5mm}
---

```{r setup, include=F,eval=T}
# DEE: This chunk was set up with the aid of ChatGPT
#      The intent is to load updates quietly thus not
#      spending undue time with the logistics of getting 
#      setup. 

options(repos = c(CRAN = "https://cran.stat.auckland.ac.nz/"))

# Required packages
required_packages <- c("conflicted", "ggplot2", "dplyr", "class",  
                       "tidyverse", "flextable", "skimr", "GGally",
                       "MASS", "car", "formatR", "mice","tinytex" ,
                       "caret", "gridExtra", "fastDummies" ,"leaps")

# Install and load missing packages in a single step and quietly
for (pkg in required_packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
  }
  library(pkg, character.only = TRUE)  # Load package after installation check
}

conflict_prefer("filter", "dplyr"); conflict_prefer("select", "dplyr")

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, width = 70)

```

```{r just-checkin, include=F, eval=F}
# is the folder and file structure 
# constructed correctly? 
dir.exists("../code/")
file.exists("../code/question1.Rmd")
file.exists("../code/question2.Rmd")
file.exists("../code/question3.Rmd")

```

# Load all Data 

```{r load-dataset, eval=T, include=T}

# Load and preprocess dataset
# eval=TRUE, as agreed to on 20250313. 
#
  zip_path <- "../data/datasets.zip"
  if (file.exists(zip_path)) {
    braking <- read.csv(unz(zip_path, "braking.csv"))
    income_dateset  <- read.csv(unz(zip_path, "income.csv"))
    possums <- read.csv(unz(zip_path, "possums.csv"))
  } else {
    stop(paste(zip_path, " not found."))
  }

``` 

```{r common-functions, eval=T, include=F}

# this function is not used in this version
#
remove_outliers <- function(df, col) {        
  outliers <- boxplot.stats(df[[col]])$out  #  outliers for col
  if (length(outliers) > 0) {               #  remove if outliers 
    df <- df |> filter(!(df[[col]] %in% outliers))
  }
  return(df)
}

# This function is used in the question to make income_1 from income_0
#
remove_outliers_IQR <- function(df, col, multiplier = 5, upper_cap = Inf) {        
# Calculate IQR (Quartile distance)
  Q1 <- quantile(df[[col]], 0.25, na.rm = TRUE)  # The first quartile
  Q3 <- quantile(df[[col]], 0.75, na.rm = TRUE)  # The third quartile
  IQR_value <- Q3 - Q1  # IQR value
  
  # set lower_bound and upper_bound, upper_cap can be manually set
  lower_bound <- Q1 - multiplier * IQR_value  
  upper_bound <- min(Q3 + multiplier * IQR_value, upper_cap)  # upper_cap can be set manually
  # print(upper_bound)
  # filter outliers
  df_clean <- df |> filter(df[[col]] >= lower_bound & df[[col]] <= upper_bound)
  
  return(df_clean)
}

# this function is not used in this version
#
capture_name <- function(mdl) {
  name <- deparse(substitute(mdl))
  return(name)
}

# this function is not used in this version
#
step_analysis <- function(mdl) {      
   
  lm_form   <- formula(mdl)                    # formula 
  good_form <- length(all.vars(lm_form)) > 1  # bool : not just the intercept
  print(good_form)
  print(lm_form)
  
  if (good_form) {

    print(summary(mdl))
    print(vif(mdl))  
    
  } else {

    cat("The stepwise regression resulted in an intercept-only model (",
        deparse(lm_form), ")\nmeaning none of the predictors were statistically significant.\n") 
  }
}

```

# Braking Distance


```{r load-question1,child="../code/question1.Rmd", eval=T}
```

# Filipino Household Income

```{r load-question2, child="../code/question2.Rmd", eval=T}
```

# Predicting Possum Age

```{r load-question3, child="../code/question3.Rmd", eval=T}
```
